In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv ('train.csv')
#информация о типах данных
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
#Первые пять строк датасета
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
#Расчет количества пропусков
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
#Среднее значение возраста
mean_Age=df['Age'].mean()
print(mean_Age)

29.69911764705882

In [ ]:
#Среднее значение стоимости
mean_Fare=df['Fare'].mean()
print(mean_Fare)

32.204207968574636

In [ ]:
#Количество выживших и погибших
df['Survived'].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [ ]:
#Расчет количества пассажиров в каждом классе и число выживших в них в виде двух датасетов
df_Pclass=df.groupby("Pclass")["Survived"].sum()
all_Pclass=df["Pclass"].value_counts()
print (df_Pclass)
print (all_Pclass)

Pclass
1    136
2     87
3    119
Name: Survived, dtype: int64
Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [ ]:
#Объединение датасетов и его сортировка по индексу
two_df = pd.concat([all_Pclass, df_Pclass],axis=1).sort_index()
print(two_df)

        count  Survived
Pclass
1         216       136
2         184        87
3         491       119

In [ ]:
#Процент выживаемости у каждого класса пассажиров
two_df['Survived']/two_df['count']*100

Pclass
1    62.962963
2    47.282609
3    24.236253
dtype: float64

In [ ]:
#Датасет женщин
Women=df.loc[df["Sex"] == 'female', "Name"]

In [ ]:
#Датасет мужчин
Men=df.loc[df["Sex"] == 'male', "Name"]

In [ ]:
#Самое популярное женское имя на корабле
Women_name=Women.str.split(' ',expand=True,n=3)[2].value_counts()
print(Women_name.index[0]+' '+Women_name.astype('str').iloc[0]+' раз встречается среди женщин')

William 13 раз встречается среди женщин

In [ ]:
#Cамое популярное мужское имя на корабле
Men_name=Men.str.split(' ',expand=True,n=3)[2].value_counts()
print(Men_name.index[0]+' '+Men_name.astype('str').iloc[0]+' раз встречается среди мужчин')

William 35 раз встречается среди мужчин

In [ ]:
#Cамое популярное женское имя в первом классе
Women_1=df.loc[(df["Sex"] == 'female') & (df["Pclass"] == 1), "Name"]
Women_name_1=Women_1.str.split(' ',expand=True,n=3)[2].value_counts()
print(Women_name_1.index[0]+' '+Women_name_1.astype('str').iloc[0]+' раз встречается среди женщин первого класса')

John 4 раз встречается среди женщин первого класса

In [ ]:
#Cамое популярное женское имя во втором классе
Women_2=df.loc[(df["Sex"] == 'female') & (df["Pclass"] == 2), "Name"]
Women_name_2=Women_2.str.split(' ',expand=True,n=3)[2].value_counts()
print(Women_name_2.index[0]+' '+Women_name_2.astype('str').iloc[0]+' раз встречается среди женщин второго класса')

William 6 раз встречается среди женщин второго класса

In [ ]:
#Cамое популярное женское имя в третьем классе
Women_3=df.loc[(df["Sex"] == 'female') & (df["Pclass"] == 3), "Name"]
Women_name_3=Women_3.str.split(' ',expand=True,n=3)[2].value_counts()
print(Women_name_3.index[0]+' '+Women_name_3.astype('str').iloc[0]+' раз встречается среди женщин третьего класса')

Anna 7 раз встречается среди женщин третьего класса

In [ ]:
#Cамое популярное мужское имя в первом классе
Men_1=df.loc[(df["Sex"] == 'male') & (df["Pclass"] == 1), "Name"]
Men_name_1=Men_1.str.split(' ',expand=True,n=3)[2].value_counts()
print(Men_name_1.index[0]+' '+Men_name_1.astype('str').iloc[0]+' раз встречается среди мужчин первого класса')

William 11 раз встречается среди мужчин первого класса

In [ ]:
#Cамое популярное мужское имя во втором классе
Men_2=df.loc[(df["Sex"] == 'male') & (df["Pclass"] == 2), "Name"]
Men_name_2=Men_2.str.split(' ',expand=True,n=3)[2].value_counts()
print(Men_name_2.index[0]+' '+Men_name_2.astype('str').iloc[0]+' раз встречается среди мужчин второго класса')

William 9 раз встречается среди мужчин второго класса

In [ ]:
#Cамое популярное мужское имя в третьем классе
Men_3=df.loc[(df["Sex"] == 'male') & (df["Pclass"] == 3), "Name"]
Men_name_3=Men_3.str.split(' ',expand=True,n=3)[2].value_counts()
print(Men_name_3.index[0]+' '+Men_name_3.astype('str').iloc[0]+' раз встречается среди мужчин третьего класса')

William 15 раз встречается среди мужчин третьего класса

In [ ]:
#Часть таблицы с пассажирами, возраст которых больше 44 лет
df.loc[df["Age"] > 44]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C
...,...,...,...,...,...,...,...,...,...,...,...,...
857,858,1,1,"Daly, Mr. Peter Denis",male,51.0,0,0,113055,26.5500,E17,S
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,NaN,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C

In [ ]:
#Часть таблицы с пассажирами, возраст которых меньше 44 лет и которые мужского пола
df.loc[(df["Age"] < 44)&(df['Sex']=='male')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.250,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.050,NaN,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.075,NaN,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.050,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.275,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.500,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.050,NaN,S
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.000,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.750,NaN,Q

In [ ]:
#n-местные кабины (в которых было 1,2, 3, 4 человека)
df_Cabin=df['Cabin'].value_counts()
list_Cabin_4=df_Cabin.index[df_Cabin == 4].tolist()
list_Cabin_3=df_Cabin.index[df_Cabin == 3].tolist()
list_Cabin_2=df_Cabin.index[df_Cabin == 2].tolist()
list_Cabin_1=df_Cabin.index[df_Cabin == 1].tolist()
print(', '.join(list_Cabin_4)+' - 4-хместные кабины\n' +', '.join(list_Cabin_3)+' - 3-хместные кабины\n'+', '.join(list_Cabin_2)+' - 2-хместные кабины\n'+', '.join(list_Cabin_1)+' - 1-местные кабины')

G6, C23 C25 C27, B96 B98 - 4-хместные кабины
F2, D, E101, C22 C26, F33 - 3-хместные кабины
C83, C123, B28, D26, B58 B60, E33, D33, C52, F G73, B77, C93, B5, D17, E24, E8, E121, B35, E44, C92, C78, B20, C125, E67, D35, F4, C2, D36, C65, C124, B18, B57 B59 B63 B66, B49, B22, E25, D20, C68, B51 B53 B55, C126 - 2-хместные кабины
E46, C85, D56, B78, B30, D10 D12, A5, E31, C103, A6, D7, C118, C99, A19, D47, F E69, C7, C54, E36, E34, C106, T, E40, C91, C32, B94, A31, B80, C87, D15, B4, C49, A7, B19, A32, B86, C110, E63, E12, D21, E38, C111, C104, A34, E10, C128, C82, D37, E50, B73, C95, C30, B37, C101, A16, C70, A10, A20, D19, E68, B41, D9, D50, B38, B39, C86, B79, D46, A14, B71, E58, A26, D48, B50, A23, F G63, C62 C64, C45, C90, D45, B101, C46, D30, D11, D49, E77, F38, D6, B3, B82 B84, A36, B102, B69, E49, C47, D28, E17, A24, C50, B42, C148 - 1-местные кабины

In [ ]:
#Количество 4-местных кабин
len(list_Cabin_4)

3

In [ ]:
#Количество 3-местных кабин
len(list_Cabin_3)

5

In [ ]:
#Количество 2-местных кабин
len(list_Cabin_2)

38

In [ ]:
#Количество 1-местных кабин
len(list_Cabin_1)

101